import {
  ShoppingCartIcon,
  HomeIcon,
  WifiIcon,
  DevicePhoneMobileIcon,
  FilmIcon,
  AcademicCapIcon,
  GiftIcon,
  PaperAirplaneIcon,
  ScissorsIcon,
  WrenchIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  BriefcaseIcon,
  CurrencyDollarIcon,
  BuildingLibraryIcon,
  ArrowTrendingUpIcon,
  IdentificationIcon,
  WalletIcon,
  CreditCardIcon,
  BanknotesIcon,
  Squares2X2Icon,
  EllipsisHorizontalIcon,
  StarIcon,
  HeartIcon,
  BookmarkIcon,
  FlagIcon,
  TagIcon,
  LightBulbIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  RocketLaunchIcon,
  BoltIcon,
  FireIcon,
  TrophyIcon,
  HandRaisedIcon,
  BeakerIcon,
  CpuChipIcon,
  CircleStackIcon,
  MapPinIcon,
  MusicalNoteIcon,
  BookOpenIcon,
  DocumentTextIcon,
  ShieldCheckIcon,
} from '@heroicons/vue/24/outline'
import type { FunctionalComponent } from 'vue'

/**
 * Carte des icônes synchronisée avec la version mobile (icon_mapper.dart).
 *
 * Toutes les clés du mapper mobile sont présentes ici.
 * Des alias supplémentaires sont gardés pour la rétrocompatibilité
 * mais le picker n'utilise que les clés canoniques.
 */
export const ICON_MAP: Record<string, FunctionalComponent> = {
  // ── Clés canoniques mobile (51 clés) ──────────────────────────
  food: BuildingStorefrontIcon,
  transport: MapPinIcon,
  shopping: ShoppingCartIcon,
  entertainment: FilmIcon,
  health: HeartIcon,
  bills: DocumentTextIcon,
  other: EllipsisHorizontalIcon,
  salary: BriefcaseIcon,
  freelance: CurrencyDollarIcon,
  investment: ArrowTrendingUpIcon,
  gift: GiftIcon,
  checking: BuildingLibraryIcon,
  savings: BanknotesIcon,
  cash: BanknotesIcon,
  home: HomeIcon,
  education: AcademicCapIcon,
  travel: PaperAirplaneIcon,
  subscription: IdentificationIcon,
  insurance: ShieldCheckIcon,
  pets: HeartIcon,
  clothing: TagIcon,
  utilities: BoltIcon,
  phone: DevicePhoneMobileIcon,
  internet: WifiIcon,
  gym: HeartIcon,
  coffee: FireIcon,
  groceries: BuildingStorefrontIcon,
  restaurant: BuildingStorefrontIcon,
  bar: FireIcon,
  taxi: MapPinIcon,
  bus: MapPinIcon,
  train: MapPinIcon,
  parking: MapPinIcon,
  gas: FireIcon,
  maintenance: WrenchIcon,
  beauty: ScissorsIcon,
  books: BookOpenIcon,
  music: MusicalNoteIcon,
  music_note: MusicalNoteIcon,
  games: SparklesIcon,
  sports: TrophyIcon,
  charity: HandRaisedIcon,
  tax: BuildingLibraryIcon,
  bonus: StarIcon,
  refund: ArrowTrendingUpIcon,
  dividend: ArrowTrendingUpIcon,
  rental: HomeIcon,

  // ── Alias rétrocompatibilité (clés web historiques) ────────────
  shopping_cart: ShoppingCartIcon,
  local_grocery_store: BuildingStorefrontIcon,
  local_gas_station: FireIcon,
  local_bar: FireIcon,
  local_cafe: FireIcon,
  local_taxi: MapPinIcon,
  local_parking: MapPinIcon,
  directions_car: MapPinIcon,
  directions_bus: MapPinIcon,
  local_hospital: HeartIcon,
  receipt_long: DocumentTextIcon,
  movie: FilmIcon,
  school: AcademicCapIcon,
  card_giftcard: GiftIcon,
  flight: PaperAirplaneIcon,
  content_cut: ScissorsIcon,
  build: WrenchIcon,
  store: BuildingStorefrontIcon,
  cake: CakeIcon,
  work: BriefcaseIcon,
  attach_money: CurrencyDollarIcon,
  account_balance: BuildingLibraryIcon,
  trending_up: ArrowTrendingUpIcon,
  card_membership: IdentificationIcon,
  account_balance_wallet: WalletIcon,
  credit_card: CreditCardIcon,
  payments: BanknotesIcon,
  phone_android: DevicePhoneMobileIcon,
  wifi: WifiIcon,
  more_horiz: EllipsisHorizontalIcon,
  star: StarIcon,
  favorite: HeartIcon,
  bookmark: BookmarkIcon,
  flag: FlagIcon,
  label: TagIcon,
  lightbulb: LightBulbIcon,
  extension: PuzzlePieceIcon,
  auto_awesome: SparklesIcon,
  rocket_launch: RocketLaunchIcon,
  bolt: BoltIcon,
  volunteer_activism: HandRaisedIcon,
  science: BeakerIcon,
  memory: CpuChipIcon,
  token: CircleStackIcon,
  category: Squares2X2Icon,
  widgets: Squares2X2Icon,
  medical_services: HeartIcon,
  fitness_center: HeartIcon,
  sports_esports: SparklesIcon,
  sports_soccer: TrophyIcon,
  hotel: HomeIcon,
  apartment: HomeIcon,
  fastfood: CakeIcon,
  checkroom: TagIcon,
  spa: HeartIcon,
  self_improvement: HeartIcon,
  child_care: HeartIcon,
  beach_access: PaperAirplaneIcon,
  local_laundry_service: HomeIcon,
  celebration: TrophyIcon,
  emoji_events: TrophyIcon,
  military_tech: TrophyIcon,
  workspace_premium: TrophyIcon,
  diamond: StarIcon,
  psychology: LightBulbIcon,
  biotech: BeakerIcon,
  redeem: GiftIcon,
  menu_book: BookOpenIcon,
  subscriptions: IdentificationIcon,
  security: ShieldCheckIcon,
  laptop_mac: CurrencyDollarIcon,
  pie_chart: ArrowTrendingUpIcon,
  replay: ArrowTrendingUpIcon,
}

export function getIcon(iconKey: string | null | undefined): FunctionalComponent {
  if (!iconKey) return EllipsisHorizontalIcon
  return ICON_MAP[iconKey.toLowerCase()] ?? EllipsisHorizontalIcon
}

/**
 * Clés disponibles dans le picker — uniquement les clés canoniques
 * qui existent aussi dans le mapper mobile Flutter.
 */
export function getAvailableIconKeys(): string[] {
  return PICKER_ICON_KEYS
}

export const PICKER_ICON_KEYS: string[] = [
  // Dépenses
  'food', 'groceries', 'restaurant', 'coffee', 'bar',
  'transport', 'gas', 'parking', 'taxi', 'bus', 'train',
  'shopping', 'clothing',
  'home', 'rental', 'utilities', 'phone', 'internet',
  'entertainment', 'music', 'games', 'sports',
  'health', 'gym', 'beauty', 'pets',
  'education', 'books',
  'travel',
  'bills', 'subscription', 'insurance', 'tax',
  'maintenance',
  'charity',
  'other',
  // Revenus
  'salary', 'freelance', 'investment', 'bonus',
  'gift', 'refund', 'dividend',
]
