import {
  ShoppingCartIcon,
  HomeIcon,
  WifiIcon,
  DevicePhoneMobileIcon,
  FilmIcon,
  AcademicCapIcon,
  GiftIcon,
  PaperAirplaneIcon,
  ScissorsIcon,
  WrenchIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  BriefcaseIcon,
  CurrencyDollarIcon,
  BuildingLibraryIcon,
  ArrowTrendingUpIcon,
  IdentificationIcon,
  WalletIcon,
  CreditCardIcon,
  BanknotesIcon,
  Squares2X2Icon,
  EllipsisHorizontalIcon,
  StarIcon,
  HeartIcon,
  BookmarkIcon,
  FlagIcon,
  TagIcon,
  LightBulbIcon,
  PuzzlePieceIcon,
  SparklesIcon,
  RocketLaunchIcon,
  BoltIcon,
  FireIcon,
  TrophyIcon,
  HandRaisedIcon,
  BeakerIcon,
  CpuChipIcon,
  CircleStackIcon,
  MapPinIcon,
  MusicalNoteIcon,
  BookOpenIcon,
} from '@heroicons/vue/24/outline'
import type { FunctionalComponent } from 'vue'

export const ICON_MAP: Record<string, FunctionalComponent> = {
  // Dépenses
  shopping_cart: ShoppingCartIcon,
  shopping: ShoppingCartIcon,
  restaurant: BuildingStorefrontIcon,
  home: HomeIcon,
  wifi: WifiIcon,
  internet: WifiIcon,
  phone_android: DevicePhoneMobileIcon,
  phone: DevicePhoneMobileIcon,
  movie: FilmIcon,
  entertainment: FilmIcon,
  school: AcademicCapIcon,
  education: AcademicCapIcon,
  card_giftcard: GiftIcon,
  gift: GiftIcon,
  flight: PaperAirplaneIcon,
  travel: PaperAirplaneIcon,
  content_cut: ScissorsIcon,
  beauty: ScissorsIcon,
  build: WrenchIcon,
  maintenance: WrenchIcon,
  store: BuildingStorefrontIcon,
  local_grocery_store: BuildingStorefrontIcon,
  groceries: BuildingStorefrontIcon,
  local_cafe: FireIcon,
  coffee: FireIcon,
  cake: CakeIcon,
  food: BuildingStorefrontIcon,

  // Revenus
  work: BriefcaseIcon,
  salary: BriefcaseIcon,
  attach_money: CurrencyDollarIcon,
  freelance: CurrencyDollarIcon,
  account_balance: BuildingLibraryIcon,
  trending_up: ArrowTrendingUpIcon,
  investment: ArrowTrendingUpIcon,
  card_membership: IdentificationIcon,
  subscription: IdentificationIcon,

  // Comptes
  account_balance_wallet: WalletIcon,
  checking: BuildingLibraryIcon,
  credit_card: CreditCardIcon,
  payments: BanknotesIcon,
  savings: BanknotesIcon,
  cash: BanknotesIcon,

  // Catégories diverses
  category: Squares2X2Icon,
  more_horiz: EllipsisHorizontalIcon,
  other: EllipsisHorizontalIcon,
  star: StarIcon,
  bonus: StarIcon,
  favorite: HeartIcon,
  bookmark: BookmarkIcon,
  flag: FlagIcon,
  label: TagIcon,
  lightbulb: LightBulbIcon,
  extension: PuzzlePieceIcon,
  auto_awesome: SparklesIcon,
  rocket_launch: RocketLaunchIcon,
  bolt: BoltIcon,
  utilities: BoltIcon,
  charity: HandRaisedIcon,
  volunteer_activism: HandRaisedIcon,
  science: BeakerIcon,
  memory: CpuChipIcon,
  token: CircleStackIcon,
  transport: MapPinIcon,
  music: MusicalNoteIcon,
  books: BookOpenIcon,

  // Fallbacks
  pets: HeartIcon,
  health: HeartIcon,
  medical_services: HeartIcon,
  fitness_center: HeartIcon,
  gym: HeartIcon,
  sports_esports: SparklesIcon,
  games: SparklesIcon,
  sports: TrophyIcon,
  insurance: BookmarkIcon,
  tax: BuildingLibraryIcon,
  refund: ArrowTrendingUpIcon,
  dividend: ArrowTrendingUpIcon,
  rental: HomeIcon,
  hotel: HomeIcon,
  parking: MapPinIcon,
  gas: FireIcon,
  local_gas_station: FireIcon,
  bar: FireIcon,
  local_bar: FireIcon,
  fastfood: CakeIcon,
  icecream: CakeIcon,
  clothing: TagIcon,
  checkroom: TagIcon,
  bus: MapPinIcon,
  train: MapPinIcon,
  taxi: MapPinIcon,
  child_care: HeartIcon,
  beach_access: PaperAirplaneIcon,
  local_laundry_service: HomeIcon,
  celebration: TrophyIcon,
  emoji_events: TrophyIcon,
  military_tech: TrophyIcon,
  workspace_premium: TrophyIcon,
  diamond: StarIcon,
  psychology: LightBulbIcon,
  self_improvement: HeartIcon,
  spa: HeartIcon,
  biotech: BeakerIcon,
  widgets: Squares2X2Icon,
  redeem: GiftIcon,
}

export function getIcon(iconKey: string | null | undefined): FunctionalComponent {
  if (!iconKey) return EllipsisHorizontalIcon
  return ICON_MAP[iconKey.toLowerCase()] ?? EllipsisHorizontalIcon
}

export function getAvailableIconKeys(): string[] {
  return Object.keys(ICON_MAP)
}
